default:
  id: "default"
  name: Macokai Pro (Accessible)
  colors:
    # primary colors
    red: "#FF6962"
    pink: "#FF6484"
    brown: "#B69668"
    orange: "#FFB33F"
    yellow: "#FFD852"
    green: "#30DF4C"
    dark_green: "027d1c"
    blue: "#5A9CFF"
    purple: "#DB90FF"
    mint: "#64D5D1"
    teal: "#5de7ff"
    dark_purple: "AF44AE"
    # base colors, sorted from darkest to lightest
    base0: "#181818"
    base1: "#1e1e1e"
    base2: "#2b2b2b"
    base3: "#434343"
    base4: "#5a5a5a"
    base5: "#717171"
    base6: "#939393"
    base7: "#dddddd"
    base8: "#E5E6E6"
    # variants (for when transparency isn't supported)
    base8x0c: "#2b2b2b" # using base2 as bg
