default:
  id: "default"
  name: Macokai Pro (Accessible)
  colors:
    # primary colors
    red: "#FF6961"
    pink: "#ff6483"
    brown: "#b59469"
    orange: "#ffb340"
    yellow: "#FFD426"
    green: "#31DE4B"
    dark_green: "027d1c"
    blue: "#409CFF"
    purple: "#DA8FFF"
    mint: "#66d4cf"
    teal: "#5de7ff"
    dark_purple: "ad44ab"
    # base colors, sorted from darkest to lightest
    base0: "#181818"
    base1: "#1e1e1e"
    base2: "#282828"
    base3: "#3f3f3f"
    base4: "#5a5a5a"
    base5: "#717171"
    base6: "#939393"
    base7: "#c0c0c0"
    base8: "#fcfcfc"
    # variants (for when transparency isn't supported)
    base8x0c: "#353535" # using base2 as bg
